### ISSUE TITLE
Многоуровневая архитектура Subsquid (Multi-Layered Architecture).

### ISSUE THREAD

**Issue by AnatoliyKonstantinov777** [subsquid/community#1]
https://medium.com/@Anatoly77/%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D0%B5%D0%B2%D0%B0%D1%8F-%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0-subsquid-multi-layered-architecture-ca9baca549de

![Logo_Font_3 (1)](https://user-images.githubusercontent.com/97233797/157636008-35e2dbf5-46fb-49a5-9dd9-f5007fced87f.png)

discord  31TORMINATOR#5975
twitter   @7bbdQRfLSckmUmQ
medium   @Anatoly77
Telegram  @Anatoly Law
https://github.com/AnatoliyKonstantinov777

**Comment by AnatoliyKonstantinov777** [comment]
Ok

**Comment by RaekwonIII** [comment]
This is **not** the place to share links and articles.

Please read the information in the main page: https://github.com/subsquid/community

Issues should be used to report bugs and suggest improvements to the Squid software. They are **not** the place to post or re-share content.

Thank you
