### ISSUE TITLE
Squids (APIs) and Archives.  SQD’s tokenomics.   Pre-Network Launch.  SaaS Solution.  Decentralisation of the Archive Network.  Decentralisation of Squids.  Multi-layer architecture

### ISSUE THREAD

**Issue by AnatoliyKonstantinov777** [subsquid/community#2]
https://twitter.com/7bbdQRfLSckmUmQ/status/1501582692009324548?s=20&t=gPpR2iFbRQ1zGtXC0DSNFQ
[@subsquid](https://twitter.com/subsquid)
  [#subsquid](https://twitter.com/hashtag/subsquid?src=hashtag_click)  [http://subsquid.io](https://t.co/r5Cq9bip7I) [http://t.me/subsquid](https://t.co/V5XxviW3kb)    https://twitter.com/subsquid   Squids (APIs) and Archives.  SQD’s tokenomics.   Pre-Network Launch.  SaaS Solution.  Decentralisation of the Archive Network.  Decentralisation of Squids.  Multi-layer architecture

https://pbs.twimg.com/media/FNaxcs2XoAQg9zL?format=jpg&name=medium

![image](https://user-images.githubusercontent.com/97233797/157637107-4c2013f6-c00c-4e08-87b8-0e5eda859c14.png)

**Comment by AnatoliyKonstantinov777** [comment]
Ok

**Comment by AnatoliyKonstantinov777** [comment]
Ok

**Comment by RaekwonIII** [comment]
This is **not** the place to share links and articles.

Please read the information in the main page: https://github.com/subsquid/community

Issues should be used to report bugs and suggest improvements to the Squid software. They are **not** the place to post or re-share content.

Thank you
